trainer:
  experiment_name: train_WGANGP_with_BERT # train_WGANGP_with_BERT | train_WGANGP_without_BERT
  run_name: zbot_training_on_hpc
  epochs: 10001 # 10001
  batch_size: 32
  save_interval: 500 # {GAN: 200, WGANGP_top_frequent_opcodes: 500}
  save_path: models/${model.modelmodule.model.model_name}/${data.datamodule.datasets.train.family}
