clf_module:
  _target_: src.model.classifiers.Classifiers

  k_fold: 5
  random_state: 6357

  svm_param:
    C: 5
    kernel: rbf
    usage: True

  rf_param:
    n_estimators: 50
    max_depth: 5
    usage: False

  naive_bayes_param:
    var_smoothing: 1e-9
    usage: False

  knn_param:
    n_neighbors: 6
    p: 2
    usage: False