clf_module:
  _target_: src.model.classifiers.Classifiers

  k_fold: 5
  random_state: 6357

  ocsvm_param:
    gamma: 0.01
    kernel: rbf
    nu: 0.01
    usage: True

  isoForest_param:
    bootstrap: True
    contamination: 0.01
    max_samples: 0.5
    n_estimators: 1
    usage: False

  lof_param:
    algorithm: auto
    contamination: 0.01
    leaf_size: 2
    n_neighbors: 5
    novelty: True
    p: 1
    usage: False
