# metadata specialised for each experiment
core:
  version: 0.0.1
  tags:
    - mytag

defaults:
  - _self_
  - data: default
  - model: default
  - train: default
#  - logging: default
#  - optim: default
