modelmodule:
  _target_: src.model.gan_model.GANModel # {GAN: src.model.gan_model.GANModel, WGANGP: src.model.wgangp_model.WGANGPModel}

  model:
    name: GAN  # GAN | WGAN | WGANGP
    latent_dim: 100
    lr: 0.0003  # {GAN: 0.0003, WGANGP: 0.0001}
    beta_1: 0.5
    beta_2: 0.9

  discriminator_param:
    first_output: 400
    last_output: 1
    alpha: 0.2
    activation: sigmoid
    loss: binary_crossentropy
    metrics: ['accuracy']

  critic_param:
    n_critic: 100
    last_output: 1
    filters: 64
    kernel_size: 3
    alpha: ${model.modelmodule.discriminator_param.alpha}
    padding: same

  generator_param:
    first_output: 200
    alpha: ${model.modelmodule.discriminator_param.alpha}
    momentum: 0.8
    activation: tanh
    loss: binary_crossentropy
    metrics: accuracy

    # WGAN-GP param
    filters: ${model.modelmodule.critic_param.filters}
    kernel_size: ${model.modelmodule.critic_param.kernel_size}
    padding: ${model.modelmodule.critic_param.padding}

