modelmodule:
  _target_: src.model.gan_model.GANModel # src.model.{model_script}.{model_class}

  model:
    name: GAN # GAN | WGAN | WGAN-GP
    latent_dim: 100
    lr: 0.0002
    beta_1: 0.5

  discriminator_param:
    first_output: 400
    last_output: 1
    alpha: 0.2
    activation: sigmoid
    loss: binary_crossentropy
    metrics: ['accuracy']

  generator_param:
    first_output: 200
    alpha: ${model.modelmodule.discriminator_param.alpha}
    momentum: 0.8
    activation: tanh
    loss: binary_crossentropy
    metrics: accuracy

