optim_module:
  optim_experiment_name: tuning_classifiers
  optim_run_name: OCSVM_${data.datamodule.datasets.train.family}_tuning_HPC

  ocsvm:
    nu: [0.01, 0.02, 0.03, 0.05, 0.07, 0.1, 0.2, 0.3, 0.5]
    kernel: [rbf, poly, sigmoid, linear]
    gamma: [0.001, 0.01, 0.1, 0.3, 0.5, 0.7, scale, auto]

  isolation_forest:
    n_estimators: [1, 5, 10, 15, 25, 50, 100]
    contamination: [0.01, 0.02, 0.03, 0.05, 0.07, 0.1, 0.2, 0.3, 0.4, 0.5]
    max_samples: [0.5, 0.8, 1.0, auto]
    bootstrap: [True, False]

  lof:
    n_neighbors: [1, 5, 10, 20, 30, 40, 50]
    leaf_size: [2, 5, 15, 30, 50, 100]
    algorithm: [auto]
    p: [1, 2]
    novelty: [True]
    contamination: [0.01, 0.02, 0.03, 0.05, 0.07, 0.1, 0.2, 0.3, 0.4, 0.5]
