bertmodule:
  _target_: src.model.bert.DistilBERT

  param:
    pretrained_weights: distilbert-base-uncased
    max_tokens: ${data.datamodule.datasets.train.max_file_len} # Since BERT only accepts  less than 512 tokens, `max_file_len` has to be less than 512
