w2vmodule:
  _target_: src.model.word2vec.Word2Vec

  param:
    name: Word2Vec
    architecture: winwebsec
    vector_size: 100
    window: 5
    min_count: 1
    workers: 4
    save_path: models/${word2vec.w2vmodule.param.name}/${word2vec.w2vmodule.param.name}_${word2vec.w2vmodule.param.architecture}.model
