evalmodule:
  _target_: src.best_gan_evaluate.GANEvaluator

  eval_experiment_name: eval_WGANGP_with_BERT
  eval_run_name: SVM_eval

  param:
    # always start with 0
    initial: 0

    # evaluate until reach specific model_save_intervals
    limit: 10000

    # {GAN: 200, WGANGP_top_frequent_opcodes: 500}
    increment: 500

    # Name of models, listed under conf/model/default.yaml
    architecture: WGANGP

    # Name of malware family, listed under conf/data/default.yaml
    family: zbot

    # {GAN: 51, WGAN: 201, WGAN-GP: 27} total number of models = epochs / save_interval
    total_models: 21

    batch_size: ${train.trainer.batch_size}
    train_test_split: 0.2
    models_path: models/${gan_evaluate.evalmodule.param.architecture}/${gan_evaluate.evalmodule.param.family}
