evalmodule:
  _target_: src.best_gan_evaluate.GANEvaluator

  param:
    initial: 0  # always start with 0
    limit: 13000  # evaluate until reach specific model_save_intervals
    increment: 500  # {GAN: 200, WGANGP: 500}
    architecture: WGANGP  # Name of models, listed under conf/model/default.yaml
    family: winwebsec  # Name of malware family, listed under conf/data/default.yaml
    train_test_split: 0.2
    total_models: 27  # {GAN: 51, WGAN: 201, WGAN-GP: 27} total number of models = epochs / save_interval
    models_path: models/${gan_evaluate.evalmodule.param.architecture}/${gan_evaluate.evalmodule.param.family}
    is_bert: False

  svm_param:
    k_fold: 5
    random_state: 6357
    C: 5
    kernel: rbf
