evalmodule:
  _target_: src.best_gan_evaluate.GANEvaluator

  param:
    initial: 0           # always start with 0
    limit: 10000             # evaluate until reach specific model_save_intervals
    increment: 200         # Increment must be = save_intervals in conf/train/default.yaml
    architecture: GAN    # Name of models, listed under conf/model/default.yaml
    family: winwebsec    # Name of malware family, listed under conf/data/default.yaml
    train_test_split: 0.2
    total_models: 51     # {GAN: 51, WGAN: 201, WGAN-GP: 201} total number of models = epochs / save_interval

  svm_param:
    k_fold: 5
    random_state: 6375
    C: 5
    kernel: rbf
